 @main
def main(): Unit =
  println("Advent of Code 2024")
//  Day00(0, "Testing").solve(true)
  Day01(1, "Historian Hysteria").solve(test = false)
//  Day02(2, "Red-Nosed Reports").solve(test = false)
//  Day03(3, "Mull It Over").solve(test = false, index = 0)
//  Day04(4, "Ceres Search").solve(test = false)
//  Day05(5, "Print Queue").solve(test = false)
//  Day06(6, "Guard Gallivant").solve(test = false)
//  Day07(7, "Bridge Repair").solve(test = false)
//  Day08(8, "Resonant Collinearity").solve(test = false, index = 0)
//  Day09(9, "xxx").solve(test = true)
//  Day10(10, "xxx").solve(test = true)
//  Day11(11, "xxx").solve(test = true)
//  Day12(12, "xxx").solve(test = true)
//  Day13(13, "xxx").solve(test = true)
//  Day14(14, "xxx").solve(test = true)
//  Day15(15, "xxx").solve(test = true)
//  Day16(16, "xxx").solve(test = true)
//  Day17(17, "xxx").solve(test = true)
//  Day18(18, "xxx").solve(test = true)
//  Day19(19, "xxx").solve(test = true)
//  Day20(20, "xxx").solve(test = true)
//  Day21(21, "xxx").solve(test = true)
//  Day22(22, "xxx").solve(test = true)
//  Day23(23, "xxx").solve(test = true)
//  Day24(24, "xxx").solve(test = true)
//  Day25(25, "xxx").solve(test = true)
